# Generated by Django 4.1.7 on 2023-02-25 23:05

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('category', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
