# Generated by Django 4.1.7 on 2023-02-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='model',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='uav',
            name='price',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uav',
            name='weight',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
