# Generated by Django 4.1.7 on 2023-02-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0004_alter_uav_model_alter_uav_price_alter_uav_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
