# Generated by Django 4.1.7 on 2023-02-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0005_alter_uav_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='brand',
            field=models.CharField(choices=[('test1', 'TEST1'), ('test2', 'TEST2'), ('test3', 'TEST3')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='uav',
            name='category',
            field=models.CharField(choices=[('cat1', 'Cat1'), ('cat2', 'Cat2')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='uav',
            name='model',
            field=models.CharField(choices=[('model1', 'Model1'), ('model2', 'Model2')], default=None, max_length=50),
        ),
    ]
