# Generated by Django 4.1.7 on 2023-02-26 02:25

from django.db import migrations, models
import django.utils.timezone
import uav.utils


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0006_alter_uav_brand_alter_uav_category_alter_uav_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=uav.utils.user_listing_path),
            preserve_default=False,
        ),
    ]
