# Generated by Django 4.1.7 on 2023-02-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0008_alter_uav_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
