version: "3.7"

services:
  web:
    build: .
    container_name: uav-rental
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=uavrental
      - POSTGRES_USER=volkan
      - POSTGRES_PASSWORD=test1234
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=uavrental
      - POSTGRES_USER=volkan 
      - POSTGRES_PASSWORD=test1234
    ports:
      - '5432:5432'

volumes:
  postgres_data:
